export default slideHeight => {
  return [
    {
      id: 'doorway',
      source: require('./assets/images/doorway.png'),
      style: {
        position: 'absolute',
        bottom: 30,
        right: 40,
        width: 342 * slideHeight / 3.5 / 858,
        height: slideHeight / 3.5,
      },
      position: 'bottom',
    },
    {
      id: 'flip-hart',
      source: require('./assets/images/flip-hart.png'),
      style: {
        position: 'absolute',
        bottom: 30,
        right: 20,
        width: 738 * slideHeight / 3 / 1495,
        height: slideHeight / 3,
      },
      position: 'bottom',
    },
    {
      id: 'leaf',
      source: require('./assets/images/leaf.png'),
      style: {
        position: 'absolute',
        bottom: 50,
        right: 40,
        width: 1037 * slideHeight / 4 / 1320,
        height: slideHeight / 4,
      },
      position: 'bottom',
    },
    {
      id: 'light-1',
      source: require('./assets/images/light-1.png'),
      style: {
        position: 'absolute',
        top: 0,
        left: 20,
        width: 540 * slideHeight / 2.8 / 1567,
        height: slideHeight / 2.8,
      },
      position: 'top',
    },
    {
      id: 'light-2',
      source: require('./assets/images/light-2.png'),
      style: {
        position: 'absolute',
        top: 0,
        left: 20,
        width: 811 * slideHeight / 2.8 / 1395,
        height: slideHeight / 2.8,
      },
      position: 'top',
    },
    {
      id: 'light-3',
      source: require('./assets/images/light-3.png'),
      style: {
        position: 'absolute',
        top: 0,
        left: 20,
        width: 680 * slideHeight / 2.8 / 1840,
        height: slideHeight / 2.8,
      },
      position: 'top',
    },
    {
      id: 'light-4',
      source: require('./assets/images/light-4.png'),
      style: {
        position: 'absolute',
        top: 0,
        left: 20,
        width: 729 * slideHeight / 2.8 / 1325,
        height: slideHeight / 2.8,
      },
      position: 'top',
    },
    {
      id: 'lounge-chair',
      source: require('./assets/images/lounge-chair.png'),
      style: {
        position: 'absolute',
        bottom: 40,
        right: 20,
        width: 969 * slideHeight / 3.5 / 1122,
        height: slideHeight / 3.5,
      },
      position: 'bottom',
    },
    {
      id: 'table-1',
      source: require('./assets/images/table-1.png'),
      style: {
        position: 'absolute',
        bottom: 40,
        right: 20,
        width: 1205 * slideHeight / 7 / 498,
        height: slideHeight / 7,
      },
      position: 'bottom',
    },
    {
      id: 'table-2',
      source: require('./assets/images/table-2.png'),
      style: {
        position: 'absolute',
        bottom: 40,
        right: 20,
        width: 700 * slideHeight / 5 / 509,
        height: slideHeight / 5,
      },
      position: 'bottom',
    },
    {
      id: 'vase-1',
      source: require('./assets/images/vase-1.png'),
      style: {
        position: 'absolute',
        bottom: 40,
        right: 20,
        width: 651 * slideHeight / 3 / 1241,
        height: slideHeight / 3,
      },
      position: 'bottom',
    },
    {
      id: 'vase-2',
      source: require('./assets/images/vase-2.png'),
      style: {
        position: 'absolute',
        bottom: 40,
        right: 20,
        width: 796 * slideHeight / 3 / 1526,
        height: slideHeight / 3,
      },
      position: 'bottom',
    },
    {
      id: 'plant-11',
      source: require('./assets/images/plant-11.png'),
      style: {
        position: 'absolute',
        top: 30,
        left: 20,
        width: 871 * slideHeight / 3 / 1484,
        height: slideHeight / 3,
      },
      position: 'top',
    },
    {
      id: 'plant-12',
      source: require('./assets/images/plant-12.png'),
      style: {
        position: 'absolute',
        top: 30,
        left: 20,
        width: 871 * slideHeight / 3 / 1480,
        height: slideHeight / 3,
      },
      position: 'top',
    },
    {
      id: 'plant-1',
      source: require('./assets/images/plant-1.png'),
      style: {
        position: 'absolute',
        bottom: 30,
        right: 20,
        width: 1104 * slideHeight / 2.8 / 2504,
        height: slideHeight / 2.8,
      },
      position: 'bottom',
    },
    {
      id: 'plant-8',
      source: require('./assets/images/plant-8.png'),
      style: {
        position: 'absolute',
        bottom: 30,
        right: 20,
        width: 1104 * slideHeight / 2.8 / 2504,
        height: slideHeight / 2.8,
      },
      position: 'bottom',
    },
    {
      id: 'plant-2',
      source: require('./assets/images/plant-2.png'),
      style: {
        position: 'absolute',
        bottom: 40,
        right: 20,
        width: 1029 * slideHeight / 3.3 / 1514,
        height: slideHeight / 3.3,
      },
      position: 'bottom',
    },
    {
      id: 'plant-3',
      source: require('./assets/images/plant-3.png'),
      style: {
        position: 'absolute',
        bottom: 40,
        right: 20,
        width: 1029 * slideHeight / 3.3 / 1514,
        height: slideHeight / 3.3,
      },
      position: 'bottom',
    },
    {
      id: 'plant-9',
      source: require('./assets/images/plant-9.png'),
      style: {
        position: 'absolute',
        bottom: 40,
        right: 20,
        width: 980 * slideHeight / 3.5 / 1212,
        height: slideHeight / 3.5,
      },
      position: 'bottom',
    },
    {
      id: 'plant-10',
      source: require('./assets/images/plant-10.png'),
      style: {
        position: 'absolute',
        bottom: 40,
        right: 20,
        width: 980 * slideHeight / 3.5 / 1212,
        height: slideHeight / 3.5,
      },
      position: 'bottom',
    },
    {
      id: 'plant-4',
      source: require('./assets/images/plant-4.png'),
      style: {
        position: 'absolute',
        bottom: 40,
        right: 20,
        width: 1000 * slideHeight / 4 / 801,
        height: slideHeight / 4,
      },
      position: 'bottom',
    },
    {
      id: 'plant-5',
      source: require('./assets/images/plant-5.png'),
      style: {
        position: 'absolute',
        bottom: 40,
        right: 20,
        width: 1000 * slideHeight / 4 / 801,
        height: slideHeight / 4,
      },
      position: 'bottom',
    },
    {
      id: 'plant-6',
      source: require('./assets/images/plant-6.png'),
      style: {
        position: 'absolute',
        bottom: 30,
        right: 20,
        width: 700 * slideHeight / 3.3 / 1196,
        height: slideHeight / 3.3,
      },
      position: 'bottom',
    },
    {
      id: 'plant-7',
      source: require('./assets/images/plant-7.png'),
      style: {
        position: 'absolute',
        bottom: 30,
        right: 20,
        width: 700 * slideHeight / 3.3 / 1196,
        height: slideHeight / 3.3,
      },
      position: 'bottom',
    },
    {
      id: 'plant-13',
      source: require('./assets/images/plant-13.png'),
      style: {
        position: 'absolute',
        bottom: 30,
        right: 20,
        width: 700 * slideHeight / 3.3 / 1206,
        height: slideHeight / 3.3,
      },
      position: 'bottom',
    },
    {
      id: 'plant-14',
      source: require('./assets/images/plant-14.png'),
      style: {
        position: 'absolute',
        bottom: 30,
        right: 20,
        width: 700 * slideHeight / 3.3 / 1206,
        height: slideHeight / 3.3,
      },
      position: 'bottom',
    },
    {
      id: 'plant-15',
      source: require('./assets/images/plant-15.png'),
      style: {
        position: 'absolute',
        bottom: 30,
        right: 20,
        width: 700 * slideHeight / 3.2 / 838,
        height: slideHeight / 3.2,
      },
      position: 'bottom',
    },
    {
      id: 'plant-16',
      source: require('./assets/images/plant-16.png'),
      style: {
        position: 'absolute',
        bottom: 30,
        right: 20,
        width: 700 * slideHeight / 3.2 / 838,
        height: slideHeight / 3.2,
      },
      position: 'bottom',
    },
  ]
}